### PR TITLE
add `ListEvents`

### PR DESCRIPTION
**Pull request by thesimplekid**
Add the ability to list events with filters

### CODE REVIEW

**Comment by 0xtrr** [comment]
Hi, sorry for the extremely late reply, I did not get any notifications regarding this. I'll look at this tomorrow asap!

**Comment by thesimplekid** [comment]
No worries made it for my own testing, figured I would open the PR since i had the code

**Comment by thesimplekid** [comment]
Just making this a draft as it conflicts with #1

**Comment by 0xtrr** [comment]
Thanks for the contribution @thesimplekid!

**Pull request merged**
