### PR TITLE
WIP: Nostr connect nip 46

### PR DESCRIPTION
**Pull request by thesimplekid**

### CODE REVIEW

**Comment by yukibtc** [comment]
@thesimplekid try to take a look to [nostr-connect](https://github.com/rust-nostr/nostr/blob/master/crates/nostr-sdk/examples/nostr-connect.rs) example, maybe can be useful for the NIP46 client part.

**Comment by yukibtc** [comment]
if you create a `Client` with `with_remote_signer` contructor and call `req_signer_public_key` method to request the signer pubkey (if not already added before), every method that need the keys for sign events will send a request to the signer and wait for response (with a default timeout of 180 secs, that can be changed in `Options`).

**Comment by thesimplekid** [comment]
Thank you that's much cleaner

**Comment by thesimplekid** [comment]
Basic functionality of a connect app that requests signatures of kind 1 notes from a remote signer. A connect app that can sign events and delegation requests.

Also included bumping nostr-sdk to 0.21

**Comment by 0xtrr** [comment]
Awesome, I'll need to read up on NIP-46 before I can test this feature. I updated nostr-sdk on main before checking this PR so you'll need to resolve the merge conflicts first. Sorry!

**Comment by thesimplekid** [comment]
> need to resolve the merge conflicts first. Sorry!
No worries

There is a little web app at https://connect.thesimplekid.com/ that can act as the connect app for delegation.

**Comment by thesimplekid** [comment]
No worries. Its not the full nip46, just the basic text note signing i was using for testing. So I'm fine leaving it open for now so rest of nip46 can be added in one shot.

**Comment by 0xtrr** [comment]
I'm closing this issue @thesimplekid, please open it again if you start working on it again

**Pull request closed without merging**
