### PR TITLE
Add vanity pubkey mining

### PR DESCRIPTION
**Pull request by yukibtc**
* Bump `nostr-sdk` to 0.18.0
* Fix clippy
* Propagate errors
* Add `vanity` command

### CODE REVIEW

**Comment by yukibtc** [comment]
If changes are too many to review, I'll split this PR in multiples PRs.

**Comment by 0xtrr** [comment]
Thanks for this PR @yukibtc! No that's ok, was only 4 commits.

The change re: error propagation, is this to propagate error messages from the nostr-sdk library instead of having/creating our own? Seems to clean up the code a bit which is always nice!

**Comment by yukibtc** [comment]
> Thanks for this PR @yukibtc! No that's ok, was only 4 commits.
> 
> The change re: error propagation, is this to propagate error messages from the nostr-sdk library instead of having/creating our own? Seems to clean up the code a bit which is always nice!

It's to avoid to use `.unwrap()` and show errors with too much things. 
In this way the errors will be more cleaned: `Error: InvalidChar('y')` for example.

If I have time, I'll try to further improve display error messages.

**Comment by 0xtrr** [comment]
> > Thanks for this PR @yukibtc! No that's ok, was only 4 commits.
> > The change re: error propagation, is this to propagate error messages from the nostr-sdk library instead of having/creating our own? Seems to clean up the code a bit which is always nice!
> 
> It's to avoid to use `.unwrap()` that show errors with too much things. In this way the errors will be more cleaned: `Error: InvalidChar('y')` for example.
> 
> If I have time, I'll try to further improve display error messages.

As long as the user gets an error message that says what actually went wrong, it's all good to me. I'd say we can merge this now and make improvements later on if you want to

**Comment by yukibtc** [comment]
Yes, I'll open new PRs in the future :)

**Comment by 0xtrr** [comment]
> Yes, I'll open new PRs in the future :)

Allright, appreciate the PR and help with this project!

**Pull request merged**
